### ISSUE TITLE
COALESCE

### ISSUE THREAD

**Issue by aocsa** [BlazingDB/blazingdb-calcite#9]
## issue calcite: 
sql: select n.n_nationkey, COALESCE(n.r_regionkey,-1) from main.join_res as n 

produce:
logical plan:
LogicalProject(n_nationkey=[$0], `EXPR$1=[$1]`)
  EnumerableTableScan(table=[[main, join_res]])

EXPR$1 is wrong!

@felipeblazing @aucahuasi

**Comment by williamBlazing** [comment]
Columns have been set to be able to be nullable and this no longer is an issue
